/*
 * Jframe utilizada para o professor deixar de dar uma materia
 */
package gestaoescolar.Materias;

import gestaoescolar.CadastroUsuarios.Login;
import Modelos.Usuarios.Aluno;
import Modelos.Universidade.Curso;
import Modelos.Materias.Turma;
import Modelos.Materias.MateriaemGrade;
import Modelos.Usuarios.Pessoa;
import Modelos.Usuarios.Professor;
import Modelos.Usuarios.Semestre;
import java.awt.Color;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Pedro Lucas
 */
public class TelaRetirarMateriaProf extends javax.swing.JFrame {

    int rr = 0;
    int zz = 0;
    int jj = 0;

    /**
     * Creates new form TelaGradeAluno
     */
    Curso engComp = new Curso("Engenharia de Computação", "CJM");
    Curso engEletrica = new Curso("Engenharia Eletrica", "CJM");
    Curso engProd = new Curso("Engenharia de Produção", "CJM");
    Curso engSistemas = new Curso("Sistema da Informação", "CJM");
    String matriculaAdmin;
    Pessoa login =Login.aa();
    Professor pp = null;   
    
    public TelaRetirarMateriaProf() {
        initComponents();
        labelMat.setVisible(false);
        btnMateria.setVisible(false);
        edtMateria.setVisible(false);
        TableMat.setFillsViewportHeight(true);
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        if ("Admin".equals(login.getFunção())) {
            while (matriculaAdmin==null)
                matriculaAdmin = JOptionPane.showInputDialog(this,"Digite a matricula do Professor que voce quer usar");
            
        }  
        if ("Professor".equals(login.getFunção())){
            pp = (Professor) login;
        }
        if ("Admin".equals(login.getFunção())){
            
            for (Professor prof: Professor.verProfessores()){
                if (prof.getMatricula().equals(matriculaAdmin))
                    pp = prof;
            }
        }
    }

    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TableMat = new javax.swing.JTable();
        labelMat = new javax.swing.JLabel();
        edtMateria = new javax.swing.JTextField();
        btnMateria = new javax.swing.JButton();
        labelSem = new javax.swing.JLabel();
        edtSemestre = new javax.swing.JTextField();
        btnAtualizarTabela = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 204, 204));

        jPanel1.setBackground(new java.awt.Color(255, 204, 204));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        TableMat.setBackground(new java.awt.Color(255, 204, 204));
        TableMat.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        TableMat.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Materia", "Codigo", "Semestre", "Pre requisito", "Curso"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, true, true, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        TableMat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TableMatMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(TableMat);
        if (TableMat.getColumnModel().getColumnCount() > 0) {
            TableMat.getColumnModel().getColumn(2).setPreferredWidth(50);
        }

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 10, 481, 379));

        labelMat.setText("Materia");
        jPanel1.add(labelMat, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, -1, -1));
        jPanel1.add(edtMateria, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 140, 122, 32));

        btnMateria.setBackground(new java.awt.Color(255, 204, 204));
        btnMateria.setText("Trancar Materia");
        btnMateria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMateriaActionPerformed(evt);
            }
        });
        jPanel1.add(btnMateria, new org.netbeans.lib.awtextra.AbsoluteConstraints(52, 375, 134, 15));

        labelSem.setText("Semestre");
        jPanel1.add(labelSem, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 60, 20));
        jPanel1.add(edtSemestre, new org.netbeans.lib.awtextra.AbsoluteConstraints(74, 22, 120, 31));

        btnAtualizarTabela.setBackground(new java.awt.Color(255, 204, 204));
        btnAtualizarTabela.setText("Atualizar Tabela");
        btnAtualizarTabela.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtualizarTabelaActionPerformed(evt);
            }
        });
        jPanel1.add(btnAtualizarTabela, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 180, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 779, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 402, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnMateriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMateriaActionPerformed
        Turma aaa = null;
        for (Turma iam: Turma.listaDeTurmasPInscrever()){
            if (iam.getId().equals(edtMateria.getText()) && iam.getSemestre()==Integer.valueOf(edtSemestre.getText())){
                aaa=iam;
            }
        }
        if (aaa!=null){
            System.out.println(aaa);
            Turma.listaDeTurmasPInscrever().remove(aaa);
            aaa.gravarMateriaIAMTxt();
            JOptionPane.showMessageDialog(this, "Materia excluida da lista");
        }         
    }//GEN-LAST:event_btnMateriaActionPerformed

    private void btnAtualizarTabelaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtualizarTabelaActionPerformed
        // TODO add your handling code here:
        int jj = 0, sem, z = 0;
        String nome, id = null, pre, curso;
        DefaultTableModel model = (DefaultTableModel) TableMat.getModel();
        int r = TableMat.getRowCount();

        for (int j = r; j > 0; j--) {
            model.removeRow(j - 1);
        }
        for (int i = 0; i < Turma.listaDeTurmasPInscrever().size(); i++) {
            z = 0;
            if (Turma.listaDeTurmasPInscrever().get(i).getSemestre() == Integer.valueOf(edtSemestre.getText())
                    && Turma.listaDeTurmasPInscrever().get(i).getProfessor().getMatricula().equals(pp.getMatricula())) {

                Turma abre = Turma.listaDeTurmasPInscrever().get(i);
                System.out.println(abre);
                nome = abre.getNome();
                id = abre.getId();
                pre = abre.getPre_requisito();
                curso = abre.getCurso().getNome();
                sem = abre.getSemestre();
                for (Aluno aa : Aluno.verAlunos()) {
                    for (Semestre s : aa.getHistorico().getListaDeSemestre()) {
                        for (MateriaemGrade mag : s.getListaMateriaemGrade()) {

                            if (abre.getId().equals(mag.getId()) && abre.getSemestre() == mag.getSemestre()
                                    && abre.getProfessor().getMatricula().equals(mag.getProfessor().getMatricula())
                                    && abre.getCurso().getNome().equals(mag.getCurso().getNome())) {
                                z = 1;
                            }

                        }
                    }
                }
                if (z == 0) {
                    model.addRow(new Object[]{nome, id, sem, pre, curso});
                    jj++;
                }
            }
        }

        labelMat.setVisible(true);

        btnMateria.setVisible(true);
        edtMateria.setVisible(true);
    }//GEN-LAST:event_btnAtualizarTabelaActionPerformed

    private void TableMatMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TableMatMouseClicked
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel) TableMat.getModel();
        edtMateria.setText((String) model.getValueAt(TableMat.getSelectedRow(), 1));        
    }//GEN-LAST:event_TableMatMouseClicked

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable TableMat;
    private javax.swing.JButton btnAtualizarTabela;
    private javax.swing.JButton btnMateria;
    private javax.swing.JTextField edtMateria;
    private javax.swing.JTextField edtSemestre;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelMat;
    private javax.swing.JLabel labelSem;
    // End of variables declaration//GEN-END:variables
}
