/*
 * Jframe utilizada para o professor dar uma materia a alguma turma
 */
package gestaoescolar.Materias;

import gestaoescolar.CadastroUsuarios.Login;
import Modelos.Usuarios.Aluno;
import Modelos.Universidade.Curso;
import Modelos.Materias.Turma;
import Modelos.Materias.Materia;
import Modelos.Usuarios.Pessoa;
import Modelos.Usuarios.Professor;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JScrollPane;
import javax.swing.JTextArea;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Pedro Lucas
 */
public class TelaMateriaProfessor extends javax.swing.JFrame {


    /**
     * Creates new form TelaGradeAluno
     */
    String matriculaAdmin;
    Pessoa login = Login.aa();
    public TelaMateriaProfessor() {
        initComponents();
        if ("Admin".equals(login.getFunção())) {
            while (matriculaAdmin==null)
                matriculaAdmin = JOptionPane.showInputDialog(this,"Digite a matricula do Professor que voce quer usar");
            
        }
        
                
        DefaultTableModel model = (DefaultTableModel)TableMat.getModel();
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        TableMat.setFillsViewportHeight(true);
        for (int i = 0; i < Materia.verMateria().size(); i++) {

            String nome = Materia.verMateria().get(i).getNome();
            String id = Materia.verMateria().get(i).getId();
            model.addRow(new Object[]{nome,id});

        }

    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TableMat = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        edtMateria = new javax.swing.JTextField();
        btnMostrarAlunosInscritos = new javax.swing.JButton();
        btnMateria = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        edtSemestre = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        radioComp = new javax.swing.JRadioButton();
        radioEletrica = new javax.swing.JRadioButton();
        radioSistemas = new javax.swing.JRadioButton();
        radioProd = new javax.swing.JRadioButton();
        btnTrancar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 204, 204));

        jPanel1.setBackground(new java.awt.Color(255, 204, 204));

        TableMat.setBackground(new java.awt.Color(255, 204, 204));
        TableMat.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Materia", "Codigo"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        TableMat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TableMatMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(TableMat);

        jLabel2.setText("Materia");

        btnMostrarAlunosInscritos.setBackground(new java.awt.Color(255, 153, 153));
        btnMostrarAlunosInscritos.setText("Mostrar materias e alunos inscritos");
        btnMostrarAlunosInscritos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMostrarAlunosInscritosActionPerformed(evt);
            }
        });

        btnMateria.setBackground(new java.awt.Color(255, 204, 204));
        btnMateria.setText("Inscrever Materia para professor:");
        btnMateria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMateriaActionPerformed(evt);
            }
        });

        jLabel5.setText("Semestre");

        jPanel3.setBackground(new java.awt.Color(255, 204, 204));

        radioComp.setBackground(new java.awt.Color(255, 204, 204));
        buttonGroup1.add(radioComp);
        radioComp.setText("Computação");
        radioComp.setToolTipText("Engenharia de Computação");

        radioEletrica.setBackground(new java.awt.Color(255, 204, 204));
        buttonGroup1.add(radioEletrica);
        radioEletrica.setText("Eletrica");
        radioEletrica.setToolTipText("Engenharia Eletrica");

        radioSistemas.setBackground(new java.awt.Color(255, 204, 204));
        buttonGroup1.add(radioSistemas);
        radioSistemas.setText("Sistemas");
        radioSistemas.setToolTipText("Sistema da Informação");

        radioProd.setBackground(new java.awt.Color(255, 204, 204));
        buttonGroup1.add(radioProd);
        radioProd.setText("Produção");
        radioProd.setToolTipText("Engenharia de Produção");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(radioEletrica)
                    .addComponent(radioSistemas)
                    .addComponent(radioComp)
                    .addComponent(radioProd))
                .addContainerGap(17, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(radioComp)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(radioEletrica)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(radioSistemas)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(radioProd)
                .addContainerGap())
        );

        btnTrancar.setBackground(new java.awt.Color(255, 153, 153));
        btnTrancar.setText("Deixar de dar alguma materia");
        btnTrancar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTrancarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel5)
                                            .addComponent(jLabel2))
                                        .addGap(61, 61, 61)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(edtMateria, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 134, Short.MAX_VALUE)
                                            .addComponent(edtSemestre, javax.swing.GroupLayout.Alignment.TRAILING)))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(btnTrancar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(btnMostrarAlunosInscritos, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .addGap(18, 18, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGap(0, 20, Short.MAX_VALUE)
                                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(157, 157, 157))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnMateria, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(23, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(edtSemestre, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(42, 42, 42)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(edtMateria, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addGap(29, 29, 29)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnMateria, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnTrancar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnMostrarAlunosInscritos)))
                .addGap(23, 23, 23))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnMateriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMateriaActionPerformed
        Professor pp = null;
        Curso curso = null;
        if ("Professor".equals(login.getFunção())) {
            pp = (Professor) login;

        }
        if ("Admin".equals(login.getFunção())) {
            for (Professor prof : Professor.verProfessores()) {
                if (matriculaAdmin.equals(prof.getMatricula())) {
                    pp = prof;
                }
            }
        }
        int x = 0, y = 0, z = 0;
        String k = edtSemestre.getText();

        Materia mm = Materia.VerificaMateria(edtMateria.getText());
        for (Curso c : Curso.getListadeCursos()) {
            if (radioComp.getToolTipText().equals(c.getNome()) && radioComp.isSelected()) {
                curso = c;
            }
            if (radioEletrica.getToolTipText().equals(c.getNome()) && radioEletrica.isSelected()) {
                curso = c;
            }
            if (radioProd.getToolTipText().equals(c.getNome()) && radioProd.isSelected()) {
                curso = c;
            }
            if (radioSistemas.getToolTipText().equals(c.getNome()) && radioSistemas.isSelected()) {
                curso = c;
            }
        }
        for (Turma iaam : Turma.listaDeTurmasPInscrever()) {
            if (iaam.getProfessor().getMatricula().equals(pp.getMatricula())
                    && iaam.getId().equals(mm.getId()) && iaam.getCurso().getNome().equals(curso.getNome()) && iaam.getSemestre() == Integer.valueOf(k)) {
                JOptionPane.showMessageDialog(this, "Ja ta dando essa materia");
                z = 1;
            }

        }
        if (z == 0) {
            Turma iam = new Turma(Integer.valueOf(k), pp, mm.getNome(), mm.getId(), mm.getPre_requisito(), curso);
            Turma.listaDeTurmasPInscrever().add(iam);
            iam.gravarMateriaIAMTxt();
            JOptionPane.showMessageDialog(this, "Turma inscrita");
        }
    }//GEN-LAST:event_btnMateriaActionPerformed

    private void btnMostrarAlunosInscritosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMostrarAlunosInscritosActionPerformed
        String a = "";
        for (Turma iam : Turma.listaDeTurmasPInscrever()) {
            System.out.println(iam);
            a=a+iam+"\n";
            for (Aluno aa : iam.listaDeAlunosNaTurma()) {
                System.out.println("\t"+aa);
                a=a+"       "+aa+"\n";
            }
            a=a+"\n";
        }
        JOptionPane.showMessageDialog(this, new JScrollPane (new JTextArea(a)));
        
       

    }//GEN-LAST:event_btnMostrarAlunosInscritosActionPerformed

    private void TableMatMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TableMatMouseClicked
        DefaultTableModel model = (DefaultTableModel) TableMat.getModel();
        edtMateria.setText((String) model.getValueAt(TableMat.getSelectedRow(), 1));
    }//GEN-LAST:event_TableMatMouseClicked

    private void btnTrancarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTrancarActionPerformed
        // TODO add your handling code here:
        TelaRetirarMateriaProf t1 = new TelaRetirarMateriaProf();
        t1.setResizable(false);
        t1.setVisible(true);
    }//GEN-LAST:event_btnTrancarActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable TableMat;
    private javax.swing.JButton btnMateria;
    private javax.swing.JButton btnMostrarAlunosInscritos;
    private javax.swing.JButton btnTrancar;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JTextField edtMateria;
    private javax.swing.JTextField edtSemestre;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton radioComp;
    private javax.swing.JRadioButton radioEletrica;
    private javax.swing.JRadioButton radioProd;
    private javax.swing.JRadioButton radioSistemas;
    // End of variables declaration//GEN-END:variables
}
