/*
 * Jframe utilizada para o cadastro de Professores
 */
package gestaoescolar.CadastroUsuarios;

import Modelos.Universidade.Curso;
import Modelos.Usuarios.Pessoa;
import Modelos.Usuarios.Professor;
import java.awt.Color;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import javax.swing.JTextField;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Pedro Lucas
 */


public class TelaCadProfessores extends javax.swing.JFrame {

    /**
     * Creates new form TelaCadAlunos
     */
    Curso engComp = new Curso("Engenharia de Computação", "CJM");
    Curso engEletrica = new Curso("Engenharia Eletrica", "CJM");
    Curso engProd = new Curso("Engenharia de Produção", "CJM");
    Curso engSistemas = new Curso("Sistema da Informação", "CJM");

    public TelaCadProfessores() {

        initComponents();
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        edtNome = new javax.swing.JTextField();
        edtCpf = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        edtMatric = new javax.swing.JTextField();
        edtNascimento = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        btnCadProf = new javax.swing.JButton();
        btnPrint = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 204, 204));

        jPanel1.setBackground(new java.awt.Color(255, 204, 204));

        jPanel4.setBackground(new java.awt.Color(255, 204, 204));

        jLabel1.setText("Nome");

        jLabel2.setText("CPF");

        jLabel3.setText("Matricula");

        edtNascimento.setForeground(new java.awt.Color(204, 204, 204));
        edtNascimento.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        edtNascimento.setText("DD/MM/AAAA");
        edtNascimento.setToolTipText("");
        edtNascimento.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                edtNascimentoFocusGained(evt);
            }
        });

        jLabel4.setText("Data de nascimento");

        btnCadProf.setBackground(new java.awt.Color(255, 153, 153));
        btnCadProf.setText("Cadastrar Professor");
        btnCadProf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadProfActionPerformed(evt);
            }
        });

        btnPrint.setBackground(new java.awt.Color(255, 153, 153));
        btnPrint.setText("Printar Professores");
        btnPrint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrintActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(57, 57, 57)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(edtNome, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(edtMatric, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(btnCadProf)
                        .addGap(96, 96, 96)
                        .addComponent(btnPrint))
                    .addComponent(edtCpf, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(edtNascimento, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(26, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(edtNome, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(edtCpf, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(edtMatric, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(edtNascimento, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(18, 56, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnCadProf)
                    .addComponent(btnPrint)))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(188, 188, 188))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(29, 29, 29))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 556, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

        /**
         * Metodo para cadastrar um professor
         * @param evt evento de click no botao
         */
    private void btnCadProfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadProfActionPerformed
        if (Pessoa.isCPF(edtCpf.getText())) {
            int idadeNascimento = 0;
            Calendar calendar = Calendar.getInstance();
            SimpleDateFormat formatter = new SimpleDateFormat("yyyy-MM-dd");
            String mess = null;
            String ddia = null;
            int ano = calendar.get(Calendar.YEAR);
            int mes = calendar.get(Calendar.MONTH) + 1;
            if (mes < 10) {
                mess = 0 + "" + mes;

            } else {
                mess = "" + mes;
            }
            int dia = calendar.get(Calendar.DAY_OF_WEEK);
            if (dia < 10) {
                ddia = 0 + "" + dia;

            } else {
                ddia = "" + dia;
            }

            String nascimento = edtNascimento.getText().replaceAll("/", "");
            if (nascimento.length()>7){
            String dian = nascimento.substring(0,2);
            if(Integer.valueOf(dian)<10 && dian.length()==1)
                dian=0+""+dian;
            String mesn = nascimento.substring(2,4);
            if(Integer.valueOf(mesn)<10 && mesn.length()==1)
                mesn=0+""+mesn;
            String anon = nascimento.substring(4,8);
            idadeNascimento = Integer.parseInt(anon+mesn+dian);
            }
            String dataHojeS = ano + "" + mess + "" + ddia;
            int dataHoje = Integer.parseInt(dataHojeS);
            float idadePTruncar = (dataHoje - idadeNascimento) / 10000;
            int idade = (int) idadePTruncar;
            

            Professor p1 = new Professor(edtNome.getText(), edtMatric.getText(), edtCpf.getText(), edtNascimento.getText(), idade, "Professor");
            Professor.verProfessores().add(p1);
            p1.gravarPessoaTxt();
            JOptionPane.showMessageDialog(this,"Professor matriculado com sucesso");
            edtCpf.setText("");
            edtMatric.setText("");
            edtNascimento.setText("");
            edtNome.setText("");

        } else {
            JOptionPane.showMessageDialog(this, "CPF invalido");
        }
    }//GEN-LAST:event_btnCadProfActionPerformed

    private void edtNascimentoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_edtNascimentoFocusGained
        edtNascimento.setText("");
        edtNascimento.setForeground(Color.BLACK);
        edtNascimento.setHorizontalAlignment(JTextField.LEFT);
    }//GEN-LAST:event_edtNascimentoFocusGained
    /**
     * Metodo para mostrar na tela todos os professores cadastrados
     * @param evt evento de click no botão
     */
    private void btnPrintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrintActionPerformed
            String a = "";
            for (Professor prof: Professor.verProfessores()){
            a = a+prof+"\n";
            }
            JOptionPane.showMessageDialog(this,a);
    }//GEN-LAST:event_btnPrintActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCadProf;
    private javax.swing.JButton btnPrint;
    private javax.swing.JTextField edtCpf;
    private javax.swing.JTextField edtMatric;
    private javax.swing.JTextField edtNascimento;
    private javax.swing.JTextField edtNome;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel4;
    // End of variables declaration//GEN-END:variables
}
